Elgiganten/Elgiganten/Models/Item.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Elgiganten.Models
{
    public class Item
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }

        public static int nextId = 1;

        public Item()
        {
        }

        public Item(string type, string name, string brand, string description, double price)
        {
            Id = nextId++;
            Type = type;
            Name = name;
            Brand = brand;
            Description = description;
            Price = price;
        }
        
        public override string ToString()
        {
            return $"Tak for din bestilling! Du har bestilt vare Nr: {Id.ToString()}  -  En: {Name}";
        }
    }
}

Elgiganten/Elgiganten/Pages/Item/CreateItem.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Item
{
        public class CreateItemModel : PageModel
        {

            private IItemService _itemService;

            public CreateItemModel(IItemService itemService)
            {
                _itemService = itemService;
            }

            [BindProperty]
            public Models.Item Item { get; set; }


            public IActionResult OnGet()
            {
                return Page();
            }
            public IActionResult OnPost()
            {
                if (!ModelState.IsValid)
                {
                    return Page();
                }
                _itemService.AddItem(Item);
                return RedirectToPage("GetAllItems");
            }
        }
}

Elgiganten/Elgiganten/Pages/Item/DeleteItem.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Item
{
        public class DeleteItemModel : PageModel
        {
            private IItemService _itemService;

            [BindProperty]
            public Models.Item Item { get; set; }

            public DeleteItemModel(IItemService itemService)
            {
                _itemService = itemService;
            }

            public IActionResult OnGet(int id)
            {
                Item = _itemService.GetItem(id);
                if (Item == null)
                    return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

                return Page();
            }

            public IActionResult OnPost()
            {
                Models.Item deletedItem = _itemService.DeleteItem(Item.Id);
                if (deletedItem == null)
                    return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu
                return RedirectToPage("GetAllItems");
            }
        }
}

Elgiganten/Elgiganten/Pages/Item/EditItem.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Item
{
    public class EditItemModel : PageModel
    {
        [BindProperty]
        public Models.Item Item { get; set; }

        private IItemService _itemService;

        public EditItemModel(IItemService itemService)
        {
            _itemService = itemService;
        }




        public IActionResult OnGet(int id)
        {
            Item = _itemService.GetItem(id);
            if (Item == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _itemService.UpdateItem(Item);
            return RedirectToPage("GetAllItems");
        }
    }
}

Elgiganten/Elgiganten/Pages/Item/GetAllItems.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Item
{
    public class GetAllItemsModel : PageModel
    {
        [BindProperty] public string SearchString { get; set; }
        [BindProperty] public string SearchStringType { get; set; }
        [BindProperty] public int MinPrice { get; set; }
        [BindProperty] public int MaxPrice { get; set; }

        private IItemService _itemService;

        public GetAllItemsModel(IItemService itemService)
        {
            _itemService = itemService;
        }

        public List<Models.Item> Items { get; private set; }


        public IActionResult OnGet()
        {
            Items = _itemService.GetItems().ToList();
            return Page();
        }

        public IActionResult OnPostSearchAll()
        {
            Items = _itemService.SearchAll(SearchString, SearchStringType, MinPrice, MaxPrice).ToList();
            return Page();
        }
    }
}

Elgiganten/Elgiganten/Pages/Item/CreateItem.cshtml
@page
@model Elgiganten.Pages.Item.CreateItemModel
@{
}

<form method="post">
@*    <div class="form-group">
        <label asp-for="Item.Id"></label>
        <input asp-for="Item.Id" class="form-control" />
        <span asp-validation-for="Item.Id" class="text-danger"></span>
    </div>*@
    <div class="form-group">
        <label asp-for="Item.Type"></label>
        <input asp-for="Item.Type" class="form-control" />
        <span asp-validation-for="Item.Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Name"></label>
        <input asp-for="Item.Name" class="form-control" />
        <span asp-validation-for="Item.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Brand"></label>
        <input asp-for="Item.Brand" class="form-control" />
        <span asp-validation-for="Item.Brand" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Description"></label>
        <input asp-for="Item.Description" class="form-control" />
        <span asp-validation-for="Item.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Price"></label>
        <input asp-for="Item.Price" class="form-control" />
        <span asp-validation-for="Item.Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<p>
    <a asp-page="/Item/GetAllItems">Back to List</a>
</p>

Elgiganten/Elgiganten/Pages/Item/DeleteItem.cshtml
@page
@model Elgiganten.Pages.Item.DeleteItemModel
@{
}

<h1>Delete Confirmation</h1>
<div class="alert alert-danger">
    <h5>Are you sure you want to delete Item - @Model.Item.Name</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a class="btn btn-primary" asp-page="/Item/GetAllItems">No</a>
    </form>
</div>

Elgiganten/Elgiganten/Pages/Item/EditItem.cshtml
@page
@model Elgiganten.Pages.Item.EditItemModel
@{
}

<form method="post">
    <div class="form-group">
        <label asp-for="Item.Id"></label>
        <input asp-for="Item.Id" class="form-control" />
        <span asp-validation-for="Item.Id" class="text-danger" readonly></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Type"></label>
        <input asp-for="Item.Type" class="form-control" />
        <span asp-validation-for="Item.Type" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Name"></label>
        <input asp-for="Item.Name" class="form-control" />
        <span asp-validation-for="Item.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Brand"></label>
        <input asp-for="Item.Brand" class="form-control" />
        <span asp-validation-for="Item.Brand" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Description"></label>
        <input asp-for="Item.Description" class="form-control" />
        <span asp-validation-for="Item.Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Item.Price"></label>
        <input asp-for="Item.Price" class="form-control" />
        <span asp-validation-for="Item.Price" class="text-danger"></span>
    </div>

    <p>
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </p>
</form>

<p>
    <a asp-page="/Item/GetAllItems">Back to List</a>
</p>

Elgiganten/Elgiganten/Pages/Item/GetAllItems.cshtml
@page
@model Elgiganten.Pages.Item.GetAllItemsModel
@{
}

<h1>Items</h1>

<div class="row">
    <form method="post" class="form-inline">
    <div class="col-4">
        <h5>Search Name</h5>
            <div class="input-group mb-3">
                <input asp-for="SearchString" class="form-control mr-1" placeholder="Enter Name" />
            </div>
    </div>
    <div class="col-4">
        <h5>Choose Type</h5>
            <div class="input-group mb-3">
                <select asp-for="SearchStringType" class="form-control mr-1">
                    <option value="ShowAll" selected >Show all</option>
                    <option value="PC">PC</option>
                    <option value="Konsol">Konsol</option>
                    <option value="Monitor">Monitor</option>
                    <option value="Hardware">Hardware</option>
                    <option value="Home">Home</option>
                    <option value="Tv og Lyd">Tv og Lyd</option>
                    <option value="Mobil og Tablet">Mobil og Tablet</option>
                </select>
            </div>

    </div>
    <div class="col-4">
        <h5>Filter Price</h5>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text">Min</span>
                </div>
                <input asp-for="MinPrice" class="form-control mr-1" />

                <div class="input-group-prepend">
                    <span class="input-group-text">Max</span>
                </div>
                <input asp-for="MaxPrice" class="form-control mr-1" />
                <input type="submit" asp-page-handler="SearchAll" value="Search" class="btn btn-primary" />
            </div>
    </div>
    <div class="col-4"></div>
    </form>
</div>


<table class="table table-bordered table-hover table-opacity" width="50%">
    <colgroup>
        <col style="width : 4%">
        <col style="width : 10%">
        <col style="width : 15%">
        <col style="width : 10%">
        <col style="width : 38%">
        <col style="width : 8%">
        <col style="width : 12%">
    </colgroup>
    <thead>
        <tr class="btn-secondary active">
            <th>
                Id
            </th>
            <th>
                Type
            </th>
            <th>
                Name
            </th>
            <th>
                Brand
            </th>
            <th>
                Description
            </th>
            <th>
                Price
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @if (@Model.Items != null)
        {
            foreach (var Item in Model.Items)
            {
                <tr class="btn-secondary">
                    <td>
                        @Item.Id
                    </td>
                    <td>
                        @Item.Type
                    </td>
                    <td>
                        @Item.Name
                    </td>
                    <td>
                        @Item.Brand
                    </td>
                    <td>
                        @Item.Description
                    </td>
                    <td>
                        @Item.Price
                    </td>
                    <td>
                        <a class="btn btn-light btn-sm " type="button" title="buy" asp-page="getallordres" asp-route-id="@Item.Id" onclick="buy(@Item.Id)"><i class="fa fa-shopping-cart"></i></a>
                        <a class="btn btn-primary btn-sm" type="button" title="Edit" asp-page="EditItem" asp-route-id="@Item.Id"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-danger btn-sm " type="button" title="Delete" asp-page="DeleteItem" asp-route-id="@Item.Id"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<p>
    <a class="btn btn-primary" asp-page="CreateItem"> Create a new Item </a>
</p>

<script>
    function buy(id) {
        var retVal = confirm("Er du sikker på produktvalg med id " + id);
        if (retVal == true) {
            
            window.open("/Ordre/GetAllOrdres#create");            
        }

        //window.location.replace('https://localhost:7273/Ordre/GetAllOrdres');
        //window.open("https://www.google.dk", "_blank")
       
    }
</script>