Elgiganten/Elgiganten/Models/Customer.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace Elgiganten.Models
{
    public class Customer
    {


        [Display(Name = "Kunde ID")]
        [Required(ErrorMessage = "Der Skal Angives ID")]
        [Range(typeof(int), minimum: "0", maximum: "10000", ErrorMessage = "ID skal være mellem {1} og {2}")]
        public int Id { get; set; }

        [Display(Name = "Kunde Navn")]
        [Required(ErrorMessage = "Der Skal Angives Navn på Kunde")]
        public string Name { get; set; }

        [Display(Name = "Kunde Adresse")]
        [Required(ErrorMessage = "Der Skal Angives Navn på Adresse")]
        public string Address { get; set; }

        [Display(Name = "Kunde Telefon")]
        [Required(ErrorMessage = "Der Skal Angives Telefon nummer på Kunde"), MinLength(8), MaxLength(8)]
        public string PhoneNr { get; set; }

        [Display(Name = "Kunde Email")]
        [Required(ErrorMessage = "Der Skal Angives Email på Kunde")]
        public string Email { get; set; }

        public static int nextId = 1;


            public Customer()
            {
            }

            public Customer(string name, string address, string phoneNr, string email)
            {
                Id = nextId++;
                Name = name;
                Address = address;
                PhoneNr = phoneNr;
                Email = email;
            }

        public override string ToString()
        {
            return $"Du Har KundeID: {Id.ToString()}, Adresse: {Address} Telefon-Nummer: {PhoneNr} Email: {Email}";
        }
    }
}

Elgiganten/Elgiganten/Pages/Customer/CreateCustomer.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Customer
{
    public class CreateCustomerModel : PageModel
    {
        private ICustomerService _customerservice;

        public CreateCustomerModel(ICustomerService customerService)
        {
            _customerservice = customerService;
        }

        [BindProperty]
        public Models.Customer customer { get; set; }

        
        public IActionResult OnGet()
        {
            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _customerservice.AddCustomer(customer);
            return RedirectToPage("GetAllCustomer");
        }
    }
}

Elgiganten/Elgiganten/Pages/Customer/DeleteCustomer.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Customer
{
    public class DeleteCustomerModel : PageModel
    {
        private ICustomerService _customerService;

        [BindProperty]
        public Models.Customer Customer { get; set; }

        public DeleteCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public IActionResult OnGet(int id)
        {
            Customer = _customerService.GetCustomer(id);
            if (Customer == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }

        public IActionResult OnPost()
        {
            Models.Customer deletedCustomer = _customerService.DeleteCustomer(Customer.Id);
            if (deletedCustomer == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu
            return RedirectToPage("GetAllCustomer");
        }
    }
}

Elgiganten/Elgiganten/Pages/Customer/EditCustomer.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Customer
{
    public class EditCustomerModel : PageModel
    {
        [BindProperty]
        public Models.Customer Customer { get; set; }

        private ICustomerService _customerService;

        public EditCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }


        public IActionResult OnGet(int id)
        {
            Customer = _customerService.GetCustomer(id);
            if (Customer == null)
                return RedirectToPage("/NotFound"); //NotFound er ikke defineret endnu

            return Page();
        }
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            _customerService.UpdateCustomer(Customer);
            return RedirectToPage("GetAllCustomer");
        }
    }
}

Elgiganten/Elgiganten/Pages/Customer/GetAllCustomer.cshtml.cs
using Elgiganten.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Elgiganten.Pages.Customer
{
    public class GetAllCustomerModel : PageModel
    {
        [BindProperty] public string SearchString { get; set; }

        private ICustomerService _customerService;

        public GetAllCustomerModel(ICustomerService customerService)
        {
            _customerService = customerService;
        }

        public List<Models.Customer> _customers { get; private set; }


        public IActionResult OnGet()
        {
            _customers = _customerService.GetCustomers().ToList();
            return Page();
        }

        public IActionResult OnPostNameSearch()
        {
            _customers = _customerService.NameSearch(SearchString).ToList();
            return Page();
        }
    }
}

Elgiganten/Elgiganten/Pages/Customer/CreateCustomer.cshtml
@page
@model Elgiganten.Pages.Customer.CreateCustomerModel
@{
}
<form method="post">
@*    <div class="form-group">
        <label asp-for="customer.Id"></label>
        <input asp-for="customer.Id" class="form-control" />
        <span asp-validation-for="customer.Id" class="text-danger"></span>
    </div>*@
    <div class="form-group">
        <label asp-for="customer.Name"></label>
        <input asp-for="customer.Name" class="form-control" />
        <span asp-validation-for="customer.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="customer.Address"></label>
        <input asp-for="customer.Address" class="form-control" />
        <span asp-validation-for="customer.Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="customer.PhoneNr"></label>
        <input asp-for="customer.PhoneNr" class="form-control" />
        <span asp-validation-for="customer.PhoneNr" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="customer.Email"></label>
        <input asp-for="customer.Email" class="form-control" />
        <span asp-validation-for="customer.Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

<p>
    <a asp-page="/Customer/GetAllCustomer">Back to List</a>
</p>

Elgiganten/Elgiganten/Pages/Customer/DeleteCustomer.cshtml
@page
@model Elgiganten.Pages.Customer.DeleteCustomerModel
@{
}
<h1>Delete Confirmation</h1>
<div class="alert alert-danger">
    <h5>Are you sure you want to delete Item - @Model.Customer.Name</h5>
    <form method="post">
        <button type="submit" class="btn btn-danger">Yes</button>
        <a class="btn btn-primary" asp-page="/Customer/GetAllCustomer">No</a>
    </form>
</div>

Elgiganten/Elgiganten/Pages/Customer/EditCustomer.cshtml
@page
@model Elgiganten.Pages.Customer.EditCustomerModel
@{
}
<form method="post">
    <div class="form-group">
        <label asp-for="Customer.Id"></label>
        <input asp-for="Customer.Id" class="form-control" />
        <span asp-validation-for="Customer.Id" class="text-danger" readyonly></span>
    </div>
    <div class="form-group">
        <label asp-for="Customer.Name"></label>
        <input asp-for="Customer.Name" class="form-control" />
        <span asp-validation-for="Customer.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Customer.Address"></label>
        <input asp-for="Customer.Address" class="form-control" />
        <span asp-validation-for="Customer.Address" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Customer.PhoneNr"></label>
        <input asp-for="Customer.PhoneNr" class="form-control" />
        <span asp-validation-for="Customer.PhoneNr" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Customer.Email"></label>
        <input asp-for="Customer.Email" class="form-control" />
        <span asp-validation-for="Customer.Email" class="text-danger"></span>
    </div>

    <p>
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </p>
</form>

<p>
    <a asp-page="/Customer/GetAllCustomer">Back to List</a>
</p>

Elgiganten/Elgiganten/Pages/Customer/GetAllCustomer.cshtml
@page 
@model Elgiganten.Pages.Customer.GetAllCustomerModel
@{
}
<h1>Customers</h1>

<div class="row">
    <div class="col-4"><h5>Search Name</h5></div>
    <div class="col-4"></div>
</div>

<div class="row">
    <div class="col-4">
        <form method="post" class="form-inline">
            <div class="input-group mb-3">
                <input asp-for="SearchString" class="form-control mr-1" placeholder="Enter search term" />
                <input type="submit" asp-page-handler="NameSearch" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>

    <div class="col-2"></div>
</div>

<table class="table table-bordered table-hover table-opacity" width="50%">
    <colgroup>
        <col style="width : 2%">
        <col style="width : 18%">
        <col style="width : 32%">
        <col style="width : 15%">
        <col style="width : 24%">
        <col style="width : 9%">
        <col style="width : 9%">
    </colgroup>
    <thead>
        <tr class="btn-secondary active">
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Address
            </th>
            <th>
                PhoneNR
            </th>
            <th>
                Email
            </th>
            <th>
                Actions
            </th>
        </tr>
    </thead>
    <tbody>
        @if (@Model._customers != null)
        {
            foreach (var customer in Model._customers)
            {
                <tr class="btn-secondary">
                    <td>
                        @customer.Id
                    </td>
                    <td>
                        @customer.Name
                    </td>
                    <td>
                        @customer.Address
                    </td>
                    <td>
                        @customer.PhoneNr
                    </td>
                    <td>
                        @customer.Email
                    </td>
                        
                    <td>
                        <a class="btn btn-primary btn-sm" type="button" title="Edit" asp-page="EditCustomer" asp-route-id="@customer.Id"><i class="fa fa-edit"></i></a>
                        <a class="btn btn-danger btn-sm " type="button" title="Delete" asp-page="DeleteCustomer" asp-route-id="@customer.Id"><i class="fa fa-trash"></i></a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<p>
    <a class="btn btn-primary" asp-page="CreateCustomer"> Create a new Customer </a>
</p>